apiVersion: v1
kind: ConfigMap
metadata:
  name: wham-selenium-gpt-config
  namespace: wham
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "990"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_HOST: "pgm-d9j7jo449b16v9tn.pgsql.ap-southeast-5.rds.aliyuncs.com"
  POSTGRESQL_DB: "wham_db"
  POSTGRESQL_TABLE: "chat_history"
  POSTGRESQL_CACHE_LONG_DURATION: "720"
  POSTGRESQL_CACHE_SHORT_DURATION: "6"
  NEO4J_PORT: "7687"
  NEO4J_HOST: "neo4j-wham-1.private.automation.dana.id"
  BASEURL_BUSERVICE: "https://buservice.saas.dana.id"
  BASEURL_CUSTMNG: "https://custmng.saas.dana.id"
  BASEURL_APPAYMENTMNG: "https://appaymentmng.saas.dana.id"
  BASEURL_OPENAPI: "https://api.saas.dana.id"
  MC_ENDPOINT_WHAM_AUTOBOT: "https://service.ap-southeast-5.maxcompute.aliyun.com/api"
  MC_PROJECT_WHAM_OTO: "automation_dana_dw"
  ZENDESK_ENDPOINT: "https://dana.zendesk.com"
  BO_WHAM_USERNAME: "autobot.wham01@dana.id"
